In [1]:
import numpy as np

## Creating Arrays

In [2]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
np.full(4,3.4)

array([3.4, 3.4, 3.4, 3.4])

In [5]:
a = np.array([1,2,3,3,6])
a

array([1, 2, 3, 3, 6])

In [8]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [10]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multidimensional arrays